## concurrent download request test
GET http://localhost:9000/api/v1/search/detail?uuid=z2RdkjYarVY
--headers
Accept-Ranges: 0-

###
GET http://localhost:9000/api/v1/search/detail?uuid=z2RdkjYarVY
--headers
Accept-Ranges: 0-
