# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import DownloadService_pb2 as DownloadService__pb2


class DownloadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.unary_stream(
                '/com.neu.grpc.DownloadService/download',
                request_serializer=DownloadService__pb2.DownloadRequest.SerializeToString,
                response_deserializer=DownloadService__pb2.DownloadResponse.FromString,
                )
        self.read = channel.unary_stream(
                '/com.neu.grpc.DownloadService/read',
                request_serializer=DownloadService__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=DownloadService__pb2.ReadFileResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/com.neu.grpc.DownloadService/delete',
                request_serializer=DownloadService__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=DownloadService__pb2.DeleteResourceResponse.FromString,
                )


class DownloadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.unary_stream_rpc_method_handler(
                    servicer.download,
                    request_deserializer=DownloadService__pb2.DownloadRequest.FromString,
                    response_serializer=DownloadService__pb2.DownloadResponse.SerializeToString,
            ),
            'read': grpc.unary_stream_rpc_method_handler(
                    servicer.read,
                    request_deserializer=DownloadService__pb2.ReadFileRequest.FromString,
                    response_serializer=DownloadService__pb2.ReadFileResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=DownloadService__pb2.DeleteResourceRequest.FromString,
                    response_serializer=DownloadService__pb2.DeleteResourceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.neu.grpc.DownloadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DownloadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.neu.grpc.DownloadService/download',
            DownloadService__pb2.DownloadRequest.SerializeToString,
            DownloadService__pb2.DownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.neu.grpc.DownloadService/read',
            DownloadService__pb2.ReadFileRequest.SerializeToString,
            DownloadService__pb2.ReadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.neu.grpc.DownloadService/delete',
            DownloadService__pb2.DeleteResourceRequest.SerializeToString,
            DownloadService__pb2.DeleteResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
